<?php

/**
 * Implemets hook_permission().
 */

function cronmonitor_permission() {
  return array(
    'acces cronmonitor' => array(
      'title' => t('Administer Cron Monitor'),
      'description' => t('Perform administration task for Crom Monitor.'),
      )
  );
}
/**
 * Implemets hook_menu().
 */
function cronmonitor_menu() {
    $items['admin/config/system/cronmonitor'] = array(
        'title' => 'Cron Monitor Settings',
        'type' =>  MENU_NORMAL_ITEM,     
        'page callback' => 'drupal get_form',
        'page arguments' => array('cronmonitor admin form'),
        'acces arguments' => array('administer cronmonitor'),
    );
    return $items;
}
/**
 * Administration form for Cron Monitor
 */
function cronomonitor_admin_form($form, &$form_state) {
    $form['cronomonitor enable'] = array (
        '#title' => 'checkbox',
        '#title' => t('Enable Cron Monitor.'),
        '#default_value' => variable_get('cronmonitor_enable',0),
    );
    
    $form['cronmonitor_enable'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Cron Monitor.'),
        'default_value' => variable_get('cronmonitor_enable', 0),
    );

    $form['cronmonitor_email_text'] = array(
        '#title' => t('Text to send with Cron Monitor Emails'),
        '#type' => 'textarea',
        '#description' => t ('Enter some text to send with the cron monitor email messages'),
        '#default_value' => variable_get('cronmonitor_email_text',''),
        
    );
    
    return system_settings_form($form);
  
}

/**
 * Implemets hook_cron().
 */
function cronmonitor_cron() {
  if (variable_get('cronmonitor_enable',0)){
    //sned cronmonito email.
    drupal_mail('cronmonitor', 'cronmonitor_email', 'Shane@codekarate.com', language_default());
    
  }  
}

/**
 * Implements hook mail().
 */
 function cronmonitor_mail($key, &$message, $params) {
   switch ($key) {
     case 'cronmonitor_email';
       $message['subject'] = t('this is a cron monitor report');
       $message['body'][] = t('This is a report from cron monitor on @site-name', array('@site-name' => varible_get('site_name', 'test.practicasdrupal.com')));
       $message['body'][] = t(variable_get('cronmonitor_email_text',''));
       
       break;
      }
  }
 