<?php

/**
 * Implements hook permission().
 */

function form_example_permission() {
    return array(
      'submit form_ example' => array(
        'title' => t('Submit the form_example form'),
        'description' => t('Submit the form_example form'),
      ),
    );
}

/**
 * Implements hook_menu().
 */
function form_example_menu() {
  $items = array();
  $items['form-example'] = array(
    'title' => 'My Example Form',
    'type' => MENU_NORMAL_ITEM,
    'access argument' => array('submit form example'),
    'page callback' =>'drupal get_form',
    'page arguments' => array('form_example_form'),                          
  );
   
  return $items;
}

/**
 * My example form.
 */

function form_example_form($form, &$form_state) {
  $form['mynumber'] = array(
    '#type' => 'textfield',
    '#title' => t('My number'),
    '#size' => 10,
    '#maxlenght' => 10,
    '#required' => TRUE,
    '#description' => t('Please enter a valid number'),
  );
  
  $form['mytextfield']=array(
    '#type' => 'textfield',
    '#title' => t('My Textfield'),
    '#size' => 60,
    '#maxlenght' => 128,
    '#required' => TRUE,
    );
    
  $form['mytext'] = array(
    '#title' => t('My TExtarea'),
    '#type' => 'textfield',
    '#description' => t('Enter some tex'),
    '#default value' => '',
    '#required' => TRUE,
    
  );
  
  $form['mytextfield']=array(
    '#type' => 'textfield',
    '#title' => t('My Textfield'),
    '#size' => 60,
    '#maxlenght' => 128,
    '#required' => TRUE,
    );
  
    $form['submit'] = array (
      '#type' => 'submit',
      '#value' => t('Add item'),
      
    );
    
    return $form;
}

